console.log("Padre: Não benzo de jeito nenhum.");
console.log("Chicó: Mas padre, não vejo nada de mal em se benzer o bicho.");
console.log("João Grilo: No dia em que chegou o motor novo de Antônio Morais o senhor não benzeu?");
console.log("Padre: Motor é diferente, é uma coisa que todo mundo benze cachorro é que eu nunca ouvi falar.");
console.log("Chicó: Eu acho cachorro uma coisa muito melhor do que motor.");
console.log("Padre: É, mas quem vai ficar engraçado sou eu, benzendo o cachorro.");
console.log("João Grilo: É, Chicó, o padre tem razão. Quem vai ficar engraçado é ele e uma coisa é benzer motor de Major Antônio Morais e outra é benzer cachorro de Major Antônio Morais.");
console.log("Padre: Como?");
console.log("João Grilo: Eu disse que uma coisa era motor e outra era cachorro de Major Antônio Morais.");
console.log("Padre: E o dono do cachorro é o Major Antônio Morais?");
console.log("João Grilo: É, eu não queria vir, com medo de que o senhor se zangasse, mas o Major é rico e poderoso e eu trabalho na mina dele. Com medo de perder meu emprego, fui forçado a obedecer;mas disse a Chicó: padre vai se zangar.");
console.log("Padre: Zangar que nada, João! Quem é um ministro de Deus para ter direito de se zangar? Falei por falar, mas também vocês não tinham dito de quem era o cachorro!");
console.log("João Grilo: Quer dizer que benze, não é?");
console.log("Padre: E você, o que é que acha?");
console.log("Chicó: Eu não acho nada demais!");
console.log("Padre: Nem eu, não vejo mal nenhum em se abençoar as criaturinhas de Deus!");
console.log("João Grilo: Então fica tudo na paz de Deus, com cachorro benzido e todo mundo satisfeito.");